-- CAP 6 LAB I

-- 1 
USE CURSOS_INFORMATICA;
GO

-- 2
SELECT * 
FROM CAD_SALAS 
WHERE ID_SALA NOT IN (
	SELECT ID_SALA
	FROM MOV_CURSOS
);

-- 3
SELECT *
FROM CAD_TREINAMENTOS
WHERE ID_TREINAMENTO NOT IN (
	SELECT ID_TREINAMENTO
	FROM CAD_INSTRUTORES_TREINAMENTOS
);

-- 4
SELECT * FROM CAD_PESSOAS
WHERE ID_PESSOA NOT IN (
	SELECT ID_PESSOA_ALUNO
	FROM MOV_CURSOS_ALUNOS
) AND  SN_ALUNO = 'S'; 

-- 5
SELECT *
FROM CAD_DEPTOS
WHERE ID_DEPTO NOT IN (
	SELECT ID_DEPTO
	FROM CAD_FUNCIONARIOS
);

-- 6
SELECT *
FROM CAD_CARGOS
WHERE ID_CARGO NOT IN (
	SELECT ID_CARGO
	FROM CAD_FUNCIONARIOS
);

-- 7 
SELECT *
FROM CAD_PESSOAS
WHERE ID_MUNICIPIO IN (
	SELECT ID_MUNICIPIO
	FROM CAD_MUNICIPIOS
	WHERE ID_ESTADO IN (
		SELECT ID_ESTADO
		FROM CAD_ESTADOS
		WHERE ICMS <= 7
	)
);

-

-- 9
SELECT *
FROM CAD_PESSOAS
WHERE ID_PESSOA = (
	SELECT ID_PESSOA_INSTR
	FROM CAD_INSTRUTORES
	WHERE ID_PESSOA_INSTR = (
			SELECT ID_PESSOA_INSTR
			FROM CAD_INSTRUTORES_TREINAMENTOS
			WHERE VLR_HORA = (SELECT MIN(VLR_HORA) FROM CAD_INSTRUTORES_TREINAMENTOS)
	)
);
