USE [PEDIDOS_VAZIO]
GO

-- FOREIGN KEY TB_PEDIDO(CODCLI) PARA TB_VENDEDOR
ALTER TABLE dbo.TB_PEDIDO ADD
CONSTRAINT [FK_COD_CLI_TB_CLIENTE] FOREIGN KEY(CODCLI) REFERENCES dbo.TB_CLIENTE(CODCLI);

-- FOREIGN KEY TB_PEDIDO(CODVEN) COM TB_VENDEDOR
ALTER TABLE dbo.TB_PEDIDO ADD
CONSTRAINT [FK_COD_VEN_TB_VENDEDOR] FOREIGN KEY(CODVEN) REFERENCES dbo.TB_VENDEDOR(CODVEN);

-- FOREIGN KEY TB_PRODUTO(COD_TIPO) COM TB_TIPOPRODUTO
ALTER TABLE dbo.TB_PRODUTO ADD
CONSTRAINT [FK_COD_TIPO_TB_TIPOPRODUTO_] FOREIGN KEY(COD_TIPO) REFERENCES dbo.TB_TIPOPRODUTO(COD_TIPO);

-- FOREIGN KEY TB_PRODUTO(COD_UNIDADE) COM TB_UNIDADE
ALTER TABLE dbo.TB_PRODUTO ADD
CONSTRAINT [FK_COD_UNIDADE_TB_UNIDADE_] FOREIGN KEY(COD_UNIDADE) REFERENCES dbo.TB_UNIDADE(COD_UNIDADE);

-- FOREIGN KEY TB_PRODUTO(COD_TIPO) COM TB_TIPOPRODUTO
ALTER TABLE dbo.TB_PRODUTO ADD
CONSTRAINT [COD_TIPO_TB_TIPOPRODUTO_] FOREIGN KEY(COD_TIPO) REFERENCES dbo.TB_TIPOPRODUTO(COD_TIPO);

-- FOREIGN KEY TB_ITENSPEDIDO(NUM_PEDIDO) COM TB_PEDIDO
ALTER TABLE dbo.TB_ITENSPEDIDO ADD
CONSTRAINT [NUM_ITEM_TB_PEDIDO] FOREIGN KEY(NUM_PEDIDO) REFERENCES dbo.TB_PEDIDO(NUM_PEDIDO);

-- FOREIGN KEY TB_ITENSPEDIDO(ID_PRODUTO) COM TB_PRODUTO
ALTER TABLE dbo.TB_ITENSPEDIDO ADD
CONSTRAINT [ID_PRODUTO_TB_ITENSPEDIDO] FOREIGN KEY(ID_PRODUTO) REFERENCES dbo.TB_PRODUTO(ID_PRODUTO);

-- FOREIGN KEY TB_ITENSPEDIDO(CODCOR) COM TB_COR
ALTER TABLE dbo.TB_ITENSPEDIDO ADD
CONSTRAINT [CODCOR_TB_ITENSPEDIDO] FOREIGN KEY(CODCOR) REFERENCES dbo.TB_COR(CODCOR);

-- UNIQUE UNIDADE NA TB_UNIDADE
ALTER TABLE dbo.TB_UNIDADE ADD
CONSTRAINT [UNIDADE_UNIQUE] UNIQUE (UNIDADE);

-- UNIQUE TIPO NA TB_TIPOPRODUTO
ALTER TABLE dbo.TB_TIPOPRODUTO ADD
CONSTRAINT [TIPO_UNIQUE] UNIQUE (TIPO);

-- CHECK PRECO_VENDA >= PRECO_CUSTO NA TB_PRODUTO
ALTER TABLE dbo.TB_PRODUTO ADD
CONSTRAINT [CHECK_LUCRO] CHECK (PRECO_VENDA >= PRECO_CUSTO);

-- CHECK PRECO_CUSTO > 0 NA TB_PRODUTO 
ALTER TABLE dbo.TB_PRODUTO ADD
CONSTRAINT [CHECK_CUSTO] CHECK (PRECO_CUSTO > 0);

-- CHECK QTD_REAL >= 0 NA TB_PRODUTO 
ALTER TABLE dbo.TB_PRODUTO ADD
CONSTRAINT [CHECK_QTD_REAL] CHECK (QTD_REAL >= 0);

-- CHECK QUANTIDADE >= 1 NA TB_ITENSPEDIDO
ALTER TABLE dbo.TB_ITENSPEDIDO ADD
CONSTRAINT [CHECK_QUANTIDADE] CHECK (QUANTIDADE >= 1);

-- CHECK PR_UNITARIO > 0 NA TB_ITENSPEDIDO
ALTER TABLE dbo.TB_ITENSPEDIDO ADD
CONSTRAINT [CHECK_PR_UNITARIO] CHECK (PR_UNITARIO > 0);

-- CHECK 10 > DESCONTO > 0 NA TB_ITENSPEDIDO
ALTER TABLE dbo.TB_ITENSPEDIDO ADD
CONSTRAINT [CHECK_DESCONTO] CHECK (DESCONTO > 0 AND DESCONTO < 10);

-- DEFAULT PRECO_CUSTO = 0 NA TB_PRODUTO 
ALTER TABLE dbo.TB_PRODUTO ADD
CONSTRAINT [DEFAULT_VALUE_PRECO_CUSTO] DEFAULT (0) FOR PRECO_CUSTO;

-- DEFAULT PRECO_VENDA = 0 NA TB_PRODUTO 
ALTER TABLE dbo.TB_PRODUTO ADD
CONSTRAINT [DEFAULT_VALUE_PRECO_VENDA] DEFAULT (0) FOR PRECO_VENDA;

-- DEFAULT QTD_REAL = 0 NA TB_PRODUTO 
ALTER TABLE dbo.TB_PRODUTO ADD
CONSTRAINT [DEFAULT_VALUE_QTD_REAL] DEFAULT (0) FOR QTD_REAL;

-- DEFAULT QTD_MINIMA = 0 NA TB_PRODUTO 
ALTER TABLE dbo.TB_PRODUTO ADD
CONSTRAINT [DEFAULT_VALUE_QTD_MINIMA] DEFAULT (0) FOR QTD_MINIMA;

-- DEFAULT QTD_ESTIMADA = 0 NA TB_PRODUTO 
ALTER TABLE dbo.TB_PRODUTO ADD
CONSTRAINT [DEFAULT_VALUE_QTD_ESTIMADA] DEFAULT (0) FOR QTD_ESTIMADA;

-- DEFAULT COD_TIPO = 0 NA TB_PRODUTO 
ALTER TABLE dbo.TB_PRODUTO ADD
CONSTRAINT [DEFAULT_VALUE_COD_TIPO] DEFAULT (0) FOR COD_TIPO;

-- DEFAULT COD_UNIDADE = 0 NA TB_PRODUTO 
ALTER TABLE dbo.TB_PRODUTO ADD
CONSTRAINT [DEFAULT_VALUE_COD_UNIDADE] DEFAULT (0) FOR COD_UNIDADE;

GO
