-- CAP 9 LAB I

-- 1
USE PEDIDOS;
GO

-- 2
SELECT AVG(PRECO_VENDA)
FROM TB_PRODUTO;

--3
SELECT COUNT(DISTINCT NUM_PEDIDO) AS TOTAL_PEDIDOS, MAX(VLR_TOTAL) AS MAX_VLR_TOTAL, MIN(VLR_TOTAL) AS MIN_VLR_TOTAL
FROM TB_PEDIDO;

-- 4
SELECT SUM(VLR_TOTAL)
FROM TB_PEDIDO
WHERE DATA_EMISSAO BETWEEN '2014.01.01' AND '2014.01.31';

-- 5
SELECT SUM(VLR_TOTAL)
FROM TB_PEDIDO
WHERE CODVEN = 1;

-- 6
SELECT SUM(VLR_TOTAL)
FROM TB_PEDIDO
WHERE DATA_EMISSAO BETWEEN '2014.01.01' AND '2014.01.31' AND CODVEN = (
	SELECT CODVEN
	FROM TB_VENDEDOR
	WHERE NOME = 'LEIA'
);

-- 7
SELECT SUM(VLR_TOTAL)
FROM TB_PEDIDO
WHERE DATA_EMISSAO BETWEEN '2014.01.01' AND '2014.01.31' AND CODVEN = (
	SELECT CODVEN
	FROM TB_VENDEDOR
	WHERE NOME = 'MARCELO'
);

-- 8
SELECT SUM(P.VLR_TOTAL*V.PORC_COMISSAO/100)
FROM TB_PEDIDO   AS P 
JOIN TB_VENDEDOR AS V ON P.CODVEN = V.CODVEN 
WHERE P.DATA_EMISSAO BETWEEN '2014.01.01' AND '2014.01.31' AND P.CODVEN = (
	SELECT CODVEN
	FROM TB_VENDEDOR
	WHERE NOME = 'LEIA'
);

-- 9
SELECT SUM(P.VLR_TOTAL*V.PORC_COMISSAO/100)
FROM TB_PEDIDO   AS P 
JOIN TB_VENDEDOR AS V ON P.CODVEN = V.CODVEN 
WHERE P.DATA_EMISSAO BETWEEN '2014.01.01' AND '2014.01.31' AND P.CODVEN = (
	SELECT CODVEN
	FROM TB_VENDEDOR
	WHERE NOME = 'MARCELO'
);

-- 10
SELECT V.NOME, SUM(VLR_TOTAL)
FROM TB_VENDEDOR AS V
JOIN TB_PEDIDO   AS P ON P.CODVEN = V.CODVEN
WHERE P.DATA_EMISSAO BETWEEN '2014.01.01' AND '2014.01.31'
GROUP BY V.NOME;

-- 11
SELECT C.NOME, SUM(P.VLR_TOTAL)
FROM TB_PEDIDO  AS P
JOIN TB_CLIENTE AS C ON P.CODCLI = C.CODCLI
WHERE P.DATA_EMISSAO BETWEEN '2014.01.01' AND '2014.01.31'
GROUP BY C.NOME;

-- 12
SELECT PR.DESCRICAO, IT.PR_UNITARIO, SUM(IT.QUANTIDADE) AS TOTAL
FROM TB_ITENSPEDIDO AS IT
JOIN TB_PRODUTO		AS PR ON PR.COD_PRODUTO = IT.COD_PRODUTO
GROUP BY PR.DESCRICAO, IT.PR_UNITARIO;

-- 13
SELECT VE.NOME, SUM(PE.VLR_TOTAL) AS TOTAL
FROM TB_VENDEDOR AS VE
JOIN TB_PEDIDO   AS PE ON PE.CODVEN = VE.CODVEN
WHERE PE.DATA_EMISSAO BETWEEN '2014.01.01' AND '2014.01.31'
GROUP BY VE.NOME HAVING SUM(PE.VLR_TOTAL) > 80000;

-- 14
SELECT C.NOME, SUM(P.VLR_TOTAL)
FROM TB_CLIENTE AS C
JOIN TB_PEDIDO  AS P ON C.CODCLI = P.CODCLI
WHERE P.DATA_EMISSAO BETWEEN '2014.01.01' AND '2014.01.31'
GROUP BY C.NOME HAVING SUM(P.VLR_TOTAL) > 6000;

-- 15
SELECT PR.DESCRICAO, SUM(PE.VLR_TOTAL)
FROM TB_PRODUTO		AS PR
JOIN TB_ITENSPEDIDO AS IP ON IP.COD_PRODUTO = PR.COD_PRODUTO
JOIN TB_PEDIDO		AS PE ON PE.NUM_PEDIDO = IP.NUM_PEDIDO
WHERE PE.DATA_EMISSAO BETWEEN '2014.01.01' AND '2014.01.31'
GROUP BY PR.DESCRICAO HAVING SUM(PE.VLR_TOTAL) > 16000;

-- 16
SELECT TOP 10 CL.NOME, SUM(PE.VLR_TOTAL)
FROM TB_CLIENTE AS CL
JOIN TB_PEDIDO  AS PE ON CL.CODCLI = PE.CODCLI
WHERE PE.DATA_EMISSAO BETWEEN '2014.01.01' AND '2014.01.31'
GROUP BY CL.NOME 
ORDER BY SUM(PE.VLR_TOTAL) DESC;

-- 17
SELECT TOP 10 PR.DESCRICAO, SUM(IP.PR_UNITARIO)
FROM TB_PRODUTO		AS PR
JOIN TB_ITENSPEDIDO AS IP ON IP.COD_PRODUTO = PR.COD_PRODUTO
JOIN TB_PEDIDO		AS PE ON PE.NUM_PEDIDO = IP.NUM_PEDIDO
WHERE PE.DATA_EMISSAO BETWEEN '2014.01.01' AND '2014.01.31'
GROUP BY PR.DESCRICAO
ORDER BY SUM(IP.PR_UNITARIO) DESC;

-- 18
SELECT MONTH(DATA_EMISSAO) AS MES , SUM(VLR_TOTAL) AS TOTAL
FROM TB_PEDIDO 
WHERE YEAR(DATA_EMISSAO) = 2013
GROUP BY MONTH(DATA_EMISSAO)
ORDER BY MONTH(DATA_EMISSAO);


