-- Capítulo 10

-- Laboratório I

-- 1
USE PEDIDOS
GO

-- 2
SELECT NOME, SALARIO, DATA_ADMISSAO, FORMAT(DATA_ADMISSAO, 'MMMM', 'PT-BR') AS MES
FROM TB_EMPREGADO

-- 3
SELECT CONCAT(ENDERECO,'-' ,NOME) AS [NOME + ENDERECO]
FROM TB_CLIENTE

-- 4
SELECT SUBSTRING(NOME,0,CHARINDEX(' ',NOME)) AS [PRIMEIRO NOME], FORMAT(DATA_NASCIMENTO,'dd-MM' ,'PT-BR')
FROM TB_EMPREGADO

-- 5
SELECT * FROM TB_PRODUTO
EXCEPT 
SELECT * FROM TBPROD 

-- 6
SELECT * FROM TB_PRODUTO
INTERSECT 
SELECT * FROM TBPROD 