-- CAP 8 LAB I

-- 1 
USE PEDIDOS;
GO

-- 2
UPDATE TB_CARGO
SET SALARIO_INIC = 600
WHERE CARGO = 'OFFICE BOY'

-- 3 
UPDATE TB_CARGO
SET SALARIO_INIC *= 1.10;

-- 4
UPDATE TB_EMPREGADO
SET SALARIO = (
	SELECT SALARIO_INIC 
	FROM TB_CARGO AS C
	WHERE C.COD_CARGO = TB_EMPREGADO.COD_CARGO
);

-- 5 
UPDATE TB_PRODUTO
SET PRECO_VENDA = 1.30 * PRECO_CUSTO;

-- 6
UPDATE TB_PRODUTO
SET PRECO_VENDA = 1.20 * PRECO_CUSTO
WHERE COD_TIPO = 5;

-- 7 
BEGIN TRAN

UPDATE TB_PRODUTO
SET PRECO_VENDA = 1.40 * PRECO_CUSTO
WHERE COD_TIPO = (
	SELECT COD_TIPO
	FROM TB_TIPOPRODUTO
	WHERE TIPO = 'REGUA'
);

COMMIT

-- 8 
UPDATE TB_ITENSPEDIDO
SET CODCOR = (
	SELECT DISTINCT CODCOR
	FROM TB_COR
	WHERE COR = 'LARANJA'
)
WHERE DATA_ENTREGA BETWEEN '2014.10.01' AND '2014.10.30' AND CODCOR = (
	SELECT DISTINCT CODCOR
	FROM TB_COR
	WHERE COR = 'VERMELHO'
)

-- 9
UPDATE TB_CLIENTE
SET ICMS = 12
WHERE ESTADO IN ('RJ','RO','AC','RR','MG','PR','SC','RS','MS','MT');

-- 10
UPDATE TB_CLIENTE
SET ICMS = 18
WHERE ESTADO = 'SP';

-- 11 
UPDATE TB_CLIENTE
SET ICMS = 7
WHERE ESTADO NOT IN ('RJ','RO','AC','RR','MG','PR','SC','RS','MS','MT','SP');

-- 12
BEGIN TRAN

CREATE TABLE ESTADOS
(   COD_ESTADO INT IDENTITY PRIMARY KEY,
	SIGLA CHAR(2),
	ICMS NUMERIC(4,2) );

COMMIT

-- 13
INSERT INTO ESTADOS (SIGLA, ICMS) 
SELECT DISTINCT ESTADO, ICMS FROM TB_CLIENTE
WHERE ESTADO IS NOT NULL;

-- 14
BEGIN TRAN

ALTER TABLE TB_CLIENTE
ADD COD_ESTADO INT 
CONSTRAINT COD_ESTADO FOREIGN KEY REFERENCES ESTADOS(COD_ESTADO);

COMMIT

-- 15
UPDATE TB_CLIENTE
SET COD_ESTADO = (
	SELECT COD_ESTADO 
	FROM ESTADOS
	WHERE SIGLA = TB_CLIENTE.ESTADO
);
