CREATE DATABASE PEDIDOS_VENDA;
GO
USE PEDIDOS_VENDA;
GO


CREATE TABLE TB_PRODUTO(
	COD_PRODUTO		INT IDENTITY PRIMARY KEY, 
	NOME			VARCHAR(50),
	COD_MEDIDA		INT,
	COD_CATEGORIA	INT,
	QTD_ESTOQUE		INT,
	QTD_MIN			INT,
	PRECO_CUSTO		MONEY,
	PRECO_VENDA		MONEY,
	CARACT_TEC		VARCHAR(200),
	FOTO			VARBINARY(200),

	CONSTRAINT PK_COD_PRODUTO PRIMARY KEY (COD_PRODUTO)
);


CREATE TABLE TB_UNIDADE(
	COD_UNIDADE		INT IDENTITY PRIMARY KEY,
	NOME_UNIDADE	VARCHAR(50),

	CONSTRAINT PK_COD_UNIDADE PRIMARY KEY (COD_UNIDADE)
);

CREATE TABLE TB_CATEGORIA(
	COD_CATEGORIA	INT IDENTITY PRIMARY KEY,
	NOME_CATEGORIA	VARCHAR(50),

	CONSTRAINT PK_COD_CATEGORIA PRIMARY KEY (COD_CATEGORIA)
);


INSERT INTO TB_UNIDADE (NOME_UNIDADE) 
VALUES ('PECAS'),('METROS'),('QUILOGRAMAS'),('DUZIAS'),('PACOTE'),('CAIXA');

INSERT INTO TB_CATEGORIA (NOME_CATEGORIA)
VALUES ('MOUSE'),('PEN_DRIVE'),('MONITOR_DE_VIDEO'),('TECLADO'),('CPU'),('CABO_DE_REDE');

INSERT INTO TB_PRODUTO (NOME, COD_MEDIDA, COD_CATEGORIA, QTD_ESTOQUE, QTD_MIN, PRECO_CUSTO,PRECO_VENDA)
OUTPUT INSERTED.* 
VALUES ('Caneta_Azul', 1,1,150,40,$0.50,$0.75);

INSERT INTO TB_PRODUTO (NOME, COD_MEDIDA, COD_CATEGORIA, QTD_ESTOQUE, QTD_MIN, PRECO_CUSTO,PRECO_VENDA)
OUTPUT inserted.*
VALUES ('Caneta_Verde', 1,1,50,40,$0.50,$0.75),
	   ('Caneta_Vermelha',1,1,$0,35,$0,50,$0.75),
	   ('Lapis', 1,1,400,80,$0.50,$0.80),
	   ('Regua',1,1,40,10,$1.00,$1.50);

SELECT * FROM TB_PRODUTO;

