-- CAP 7 LAB 1

-- 1
USE PEDIDOS
GO

-- 2
UPDATE TB_PRODUTO
SET PRECO_CUSTO = PRECO_CUSTO * 1.15
OUTPUT inserted.PRECO_CUSTO
WHERE COD_TIPO = 2;

-- 3
BEGIN TRAN

SELECT  PRECO_CUSTO,
		PRECO_VENDA
FROM TB_PRODUTO;

UPDATE TB_PRODUTO
SET PRECO_VENDA = PRECO_CUSTO * 1.30
OUTPUT inserted.PRECO_VENDA

COMMIT 

-- 4
BEGIN TRAN

SELECT  COD_PRODUTO,
		IPI
FROM TB_PRODUTO
WHERE COD_TIPO = 3;

UPDATE TB_PRODUTO
SET IPI = 5
OUTPUT inserted.IPI
WHERE COD_TIPO = 3;

COMMIT 

-- 5
BEGIN TRAN

SELECT  COD_PRODUTO,
		QTD_MINIMA
FROM TB_PRODUTO

UPDATE TB_PRODUTO
SET QTD_MINIMA *= 0.90
OUTPUT inserted.QTD_MINIMA;

COMMIT

-- 6
BEGIN TRAN

UPDATE TB_CLIENTE
SET ENDERECO = 'AV. CELSO GARCIA, 1234',
	BAIRRO   = 'TATUAPE',
	CIDADE	 = 'SAO PAULO',
	ESTADO   = 'SP',
	CEP		 = 03407080
OUTPUT deleted.ENDERECO, inserted.ENDERECO, deleted.BAIRRO, inserted.BAIRRO, deleted.CIDADE, inserted.CIDADE,
		deleted.ESTADO, inserted.ESTADO, deleted.CEP, inserted.CEP
WHERE CODCLI = 11;

COMMIT

-- 7
UPDATE TB_CLIENTE
SET END_COB = ENDERECO,
	BAI_COB = BAIRRO,
	CID_COB = CIDADE,
	EST_COB = ESTADO,
	CEP_COB = CEP
WHERE CODCLI = 13;

-- 8 
BEGIN TRAN

UPDATE TB_CLIENTE
SET ICMS = 12
WHERE ESTADO IN ('RJ','RO','AC','RR','MG','PR','SC','RS','MS','MT');

COMMIT

-- 9
UPDATE TB_CLIENTE
SET ICMS = 18
WHERE ESTADO = 'SP';

-- 10
UPDATE TB_CLIENTE
SET ICMS = 12
WHERE ESTADO NOT IN ('RJ','RO','AC','RR','MG','PR','SC','RS','MS','MT','SP');

-- 11
BEGIN TRAN

UPDATE TB_ITENSPEDIDO
SET DESCONTO = 7
WHERE ID_PRODUTO = 8 AND DATA_ENTREGA BETWEEN '2014.01.01' AND '2014.01.31' AND QUANTIDADE > 1000;

COMMIT

-- 12
BEGIN TRAN

UPDATE TB_ITENSPEDIDO
SET DESCONTO = 0
WHERE QUANTIDADE < 1000 AND DATA_ENTREGA > '2014.07.01' AND DESCONTO > 0;

COMMIT 

-- 13
SELECT * INTO VENDEDORES_TMP
FROM TB_VENDEDOR;

-- 14
DELETE FROM VENDEDORES_TMP WHERE CODVEN > 5;

-- 15
SELECT * INTO COPIA_PEDIDOS
FROM TB_PEDIDO;

-- 16
DELETE FROM COPIA_PEDIDOS WHERE CODVEN = 2;

-- 17
DELETE FROM COPIA_PEDIDOS WHERE DATA_EMISSAO BETWEEN '2014.01.01' AND '2014.06.30';

-- 18
DELETE FROM COPIA_PEDIDOS;

-- 19
DROP TABLE COPIA_PEDIDOS;