-- LAB I

-- 1
USE PEDIDOS;
GO

-- 2
SELECT COD_PRODUTO,
	   DESCRICAO, 
	   PRECO_CUSTO, 
	   PRECO_VENDA, 
	   PRECO_VENDA - PRECO_CUSTO AS LUCRO_UNITARIO 
FROM TB_PRODUTO;

-- 3 
SELECT COD_PRODUTO, 
	   DESCRICAO, 
	   QTD_REAL - PRECO_CUSTO AS VALOR_TOTAL_INVESTIDO
FROM TB_PRODUTO;

-- 4
SELECT NUM_PEDIDO, 
	   NUM_ITEM, 
	   COD_PRODUTO, 
	   PR_UNITARIO, 
	   QUANTIDADE, 
	   DESCONTO, 
	   PR_UNITARIO * QUANTIDADE *(1 - DESCONTO/100)			AS VALOR_UNITARIO
FROM TB_ITENSPEDIDO;

-- 5
SELECT COD_PRODUTO, 
	   DESCRICAO, 
	   PRECO_CUSTO, 
	   PRECO_VENDA, 
	   QTD_REAL * (PRECO_VENDA - PRECO_CUSTO)				AS LUCRO_ESTIMADO
FROM TB_PRODUTO;

-- 6
SELECT  COD_PRODUTO, 
	    DESCRICAO, 
		PRECO_CUSTO, 
		PRECO_VENDA, 
		PRECO_VENDA - PRECO_CUSTO							AS LUCRO_UNITARIO, 
		100 * (PRECO_VENDA - PRECO_CUSTO) / PRECO_CUSTO		AS LUCRO_UNITARIO_PERCENTUAL
FROM TB_PRODUTO
WHERE PRECO_CUSTO != 0;



-- LAB II

-- 1
USE PEDIDOS;
GO

-- 2
SELECT COD_PRODUTO, 
	   DESCRICAO, 
	   QTD_REAL - QTD_MINIMA AS [QUANTIDADE ABSOLUTA]
FROM TB_PRODUTO
WHERE QTD_REAL < QTD_MINIMA;

-- 3
SELECT COD_PRODUTO, 
	   DESCRICAO,
	   QTD_REAL
FROM TB_PRODUTO
WHERE QTD_REAL > 5000;

-- 4
SELECT COD_PRODUTO,
	   DESCRICAO,
	   PRECO_VENDA
FROM TB_PRODUTO
WHERE PRECO_VENDA < $0.50;

-- 5
SELECT NUM_PEDIDO,
	   CODCLI,
	   VLR_TOTAL
FROM TB_PEDIDO
WHERE VLR_TOTAL > $15000.00;

-- 6
SELECT COD_PRODUTO,
	   DESCRICAO,
	   QTD_REAL
FROM TB_PRODUTO
WHERE QTD_REAL >= 5000 AND QTD_REAL <= 10000;

-- 7
SELECT NUM_PEDIDO,
	   CODCLI,
	   VLR_TOTAL
FROM TB_PEDIDO
WHERE VLR_TOTAL >= $15000.00 AND VLR_TOTAL <= $25000.00;
-- WHERE VLR_TOTAL BETWEEN $15000.00 AND $25000.00;

-- 8 
SELECT COD_PRODUTO,
	   DESCRICAO,
	   QTD_REAL,
	   COD_TIPO
FROM TB_PRODUTO
WHERE QTD_REAL >= 5000 AND COD_TIPO >= 6;

-- 9 
SELECT COD_PRODUTO,
	   DESCRICAO,
	   QTD_REAL,
	   COD_TIPO
FROM TB_PRODUTO
WHERE QTD_REAL >= 5000 AND COD_TIPO = 6;

-- 10
SELECT NUM_PEDIDO,
	   CODCLI,
	   VLR_TOTAL
FROM TB_PEDIDO
WHERE VLR_TOTAL < $100.00 OR VLR_TOTAL > $100000.00; 

-- 11
SELECT  COD_PRODUTO,
		DESCRICAO,
		QTD_REAL
FROM TB_PRODUTO
WHERE QTD_REAL < 500 OR QTD_REAL > 1000;

